(function(){function wa(d){function b(d){function n(){g.onreadystatechange=g.onload=null;d.callback&&d.callback.apply(d)}var g=document.createElement("script");"undefined"!=typeof d.id&&(g.id=d.id);g.setAttribute("type","text/javascript");g.setAttribute("src",d.url);g.setAttribute("charset","utf-8");document.getElementsByTagName("head")[0].appendChild(g);g.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||n()};g.onload=g.onerror=n}function f(){for(n.zid=n.zid||
"";n.funList[0];){var d=n.funList.shift();d&&d(n.zid)}}var h=Y("__xsptplusUT_"+D),p=(new Date).getTime()+3E5;h||(d.zid=null);var n=window.__zpCMSDCB;n||(n=window.__zpCMSDCB=function(d){n.zid||n.bw||(n.bw=n.zid=n.zid||n.bw||d&&d.data||"")});n.funList=n.cE=n.funList||n.cE||[];n.bw=n.zid=n.zid||n.bw||d.zid;n.funList.push(d.fun);(n.isGet||n.ds||n.zid)&&f();n.zid||n.isTouch||n.dj||(na("__xsptplusUT_"+D,1,new Date(p),"/",Z),n.isTouch=1,n.dj=1,b({url:H("//cms.gtags.net/g?z=__zpCMSDCB")+"&a="+d.a,callback:function(){n.isGet=
1;n.ds=1;f()}}))}function aa(){var d=navigator.userAgent||"";return-1<d.indexOf("MSIE 8.0")||-1<d.indexOf("MSIE 7.0")||-1<d.indexOf("MSIE 6.0")?!0:!1}function oa(d){for(var b in d)return!1;return!0}var N=navigator.userAgent.toLowerCase()||"";if(-1<N.indexOf("spider")||-1<N.indexOf("msnbot")||-1<N.indexOf("networkbench"))return!1;var q=document,p=window,pa=navigator,S=Image,O=Array,h=encodeURIComponent,b=decodeURIComponent,ba="",I="",D="",qa,ca=0,Z,Y=function(d){d=h(d)+"=";var g=q.cookie.indexOf(d),
f="";-1<g&&(f=q.cookie.indexOf(";",g),-1==f&&(f=q.cookie.length),f=b(q.cookie.substring(g+d.length,f)));return f},na=function(d,b,f,p,G,n){d=h(d)+"="+h(b);f instanceof Date&&(d+="; expires="+f.toGMTString());p&&(d+="; path="+p);G&&(d+="; domain="+G);n&&(d+="; secure");q.cookie=d},T=function(d){var b={};if(0<d.indexOf("?")){d=d.substring(d.indexOf("?")+1);0<d.indexOf("#")&&(d=d.substring(0,d.indexOf("#")));d=d.split("&");for(var f=0;f<d.length;f++)b[d[f].split("=")[0]]=d[f].split("=")[1]}if(void 0==
b.zpclkid||""==b.zpclkid)b.zpclkid=window.__zpclkid;return b},da=function(d,b,f){d.addEventListener?d.addEventListener(b,f,!1):d.attachEvent?d.attachEvent("on"+b,f):d["on"+b]=f},H=function(d){var b="";try{b="https:"==q.location.protocol?"https:":"http:"}catch(f){}return b+d},ra=function(){var b=p.location.href;return b&&""!=b?b.replace(/\s/g," "):""},ea=function(){var b="";try{b=q.referrer}catch(g){}if(""==b)try{opener&&opener.location&&(b=opener.location.href)}catch(g){}return b&&""!=b?b.replace(/\s/g,
" "):b},xa=function(b){return b?b:(b=ra().match(/[\w-]+\.(com|net|org|gov|cc|biz|info|cn|cc|tv|hk|biz|asia|me|mobi|name|info|so|co|in|la)(\.(cn|hk))*/))&&0<b.length?b[0]:null},l=function(b){b&&(b=b.replace(/[\s#,|]/g," "));return b},F=function(b){b&&"string"==typeof b&&(b=b.replace(/^(\s|\u00A0)+/,"").replace(/(\s|\u00A0)+$/,""));return b},P=[["m.baidu","word"],["wap.baidu","word"],["opendata.baidu","wd"],["baidu","word"],["baidu","wd"],["baidu","q1"],["baidu","kw"],["google","q"],["soso","w"],["sogou",
"query"],["youdao","q"],["bing","q"],["yahoo","p"],["so.360.cn","q"],["360so","q"],["360sou","q"],["so.com","q"],["ask","q"],["3721","name"],["vent","kw"],["ucweb","keyword"],["ucweb","word"],["114so","kw"],["haosou","q"],["chinaso","q"],["zhongsou","w"],["etao.com","q"],[".sm.cn","q"]],fa=function(b){var g=/^https?:\/\/(.*?)($|\/.*)/.exec(b);if(null!=g){var f="",f=g[1];b=T(b);for(g=0;g<P.length;g++)if(0<=f.indexOf(P[g][0])&&"undefined"!=typeof b[P[g][1]])return[2,l(f),"","",l(b[P[g][1]]),""];return[3,
l(f),"","","",""]}return[3,l(b),"","","",""]};(new function(){function d(b,c){var a="rid="+c+"&zid="+I;b=0<=b.indexOf("?")?b+("&"+a):b+("?"+a);var e=document.createElement("iframe");e.setAttribute("scrolling","no");e.frameBorder="0";e.src=b;e.style.cssText="width:1px;height:1px;position:fixed;_position:absolute;left:0px;top:0px;margin:0px;padding:0px;z-index:2147483648";setTimeout(function(){try{document.body&&document.body.insertBefore(e,document.body.firstChild)}catch(a){setTimeout(arguments.callee,
13)}},13);setTimeout(function(){try{e.parentNode.removeChild(e)}catch(a){}},1E4)}var g=!1,f=!1,L=null,G=0,n=0,X=0,K=0,k=4,E="",t="",r="",z="",A="",U=0,N=0,B="",v="",J="",C="w",M=function(b){return b instanceof O&&2==b.length?b[1]:""},u="",V=xa();Z=V;var Q="",m="",R="",ga="",e="",ha="",W={},sa={_addOrganic:function(b){b instanceof O&&3==b.length&&P.push([b[1],b[2]])},_setAccount:function(b){D=u=M(b)},_setDomain:function(b){Z=V=M(b)},_setPageID:function(b){m=M(b)},_setPageType:function(b){R=M(b)},_setParams:function(b){if(b instanceof
O){var c=b.length;16<c&&(c=16);for(var a=1,d=[];a<c;)d.push(h(F(b[a]))),a++;e=d.join(",")}},_setUserID:function(b){Q=M(b)},_setMType:function(b){b instanceof O&&2==b.length&&("p"==b[1]?C="p":""==b[1]&&(C=""))},_setSiteID:function(b){ga=M(b)}},w="",ia="",ja="",ka="",la="",da=function(){if(""!=C&&!p.__zp_smartpixel_list[C+"_"+u]){var b=H("//cms.gtags.net/"+C)+"?a="+u,b=b+("&zid="+I);""!=Q&&(b+="&xid="+Q);if("w"==C){p.__zp_smartpixel_list[C+"_"+u]=!0;var c=q.createElement("iframe");c.setAttribute("scrolling",
"no");c.frameBorder="0";c.src=b;c.style.cssText="width:1px;height:1px;position:fixed;_position:absolute;left:0px;top:0px;margin:0px;padding:0px;z-index:2147483648";var a=q.createElement("iframe");a.setAttribute("scrolling","no");a.frameBorder="0";a.src="about:blank";a.style.cssText="width:1px;height:1px;position:fixed;_position:absolute;left:0px;top:0px;margin:0px;padding:0px;z-index:2147483648";setTimeout(function(){try{q.body.insertBefore(c,q.body.firstChild),q.body.insertBefore(a,q.body.firstChild)}catch(b){setTimeout(arguments.callee,
13)}},13);setTimeout(function(){try{c.parentNode.removeChild(c),a.parentNode.removeChild(a)}catch(b){}},1E4)}else if("p"==C){var e=new S;e.src=b;p.__zp_smartpixel_list[C+"_"+u]=e}}},ta=function(b){var c="",a="a="+u,a=a+("&zid="+I);""!=J&&(a=a+"&rid="+h(J));""!=Q&&(a=a+"&uid="+h(Q));if(2==b)c="imp/dasp",""!=m&&(a=a+"&pi="+m),""!=R&&(a=a+"&pt="+R),""!=e&&(a=a+"&args="+e);else if(3==b){c="imp/dasp3";p.zamplus_tag_params||(p.zamplus_tag_params={});var a=a+"&ext_args=",d;b=p.zamplus_tag_params;b=qa||b;
w="";if("object"==typeof b)for(d in b)if(b.hasOwnProperty(d)){var g=F(d),f=b[d];if("p_zp_type"==g){if("string"==typeof f||"number"==typeof f)ia=h(F(f))}else if("p_zp_uuid"==g){if("string"==typeof f||"number"==typeof f)ja=h(F(f))}else if("p_zp_conversion"==g){if("string"==typeof f||"number"==typeof f)ka=h(F(f))}else if("p_zp_convinfo"==g){if("string"==typeof f||"number"==typeof f)la=h(F(f))}else if("p_zp_prodstype"==g){if("string"==typeof f||"number"==typeof f)ha=h(F(f))}else if("p_zp_prods"==g){if(!("object"!=
typeof f||f instanceof Array||oa(f)))for(var L in f)""!=f[L]&&(W[L]=f[L])}else if(f instanceof O){for(var l in f)f.hasOwnProperty(l)&&(f[l]=h(F(f[l])));w+=h(g)+"="+f.join(",")+";"}else if("string"==typeof f||"number"==typeof f||"boolean"==typeof f)w+=h(g)+"="+h(F(f))+";"}d=""!=w?w.substring(0,w.length-1):w;a+=h(d)}""!=ia&&(a=a+"&type="+ia);""!=ja&&(a=a+"&uuid="+ja);""!=ga&&(a=a+"&siteid="+h(ga));a=a+"&vc="+G+"&vt="+n+"&vpc="+K+"&rvt="+X+"&fr="+U+"&vrt="+N+"&ot="+k;""!=E&&(a=a+"&os="+h(E));""!=t&&
(a=a+"&om="+h(t));""!=r&&(a=a+"&oc="+h(r));""!=z&&(a=a+"&ok="+h(z));""!=A&&(a=a+"&oa="+h(A));""!=v&&(a=a+"&u="+h(v));d=p.screen;a=a+"&sc="+h(d.width+"x"+d.height)+"&ch="+h(q.characterSet||q.charset)+"&la="+h(pa.language||pa.userLanguage)+"&ti="+h(q.title)+"&v=3.1.0.16";""!=B&&(a=a+"&ru="+h(B));a=a+"&t=1&r="+Math.random();d=H("//dat.gtags.net/"+c)+"?"+a;2084<d.length&&aa()&&(a=a.replace("&u="+h(v),""),d=(H("//dat.gtags.net/"+c)+"?argserror=true&"+a).substring(0,2084));return[c,d]},ua=function(b,c){try{6<=
c.length&&(k=c[0],E=c[1],t=c[2],r=c[3],z=c[4],A=c[5])}catch(e){}var a=[],a=T(v);return"undefined"!=typeof a.zpclkid||"undefined"!=typeof a.utm_source&&"undefined"!=typeof a.utm_campaign&&"undefined"!=typeof a.utm_medium?("undefined"!=typeof a.zpclkid?(t=E="zampda",r=l(a.zpclkid),z=fa(B)[4],A=""):(E=l(a.utm_source),t=l(a.utm_medium),r=l(a.utm_campaign),z="undefined"!=typeof a.utm_term?l(a.utm_term):fa(B)[4],A="undefined"!=typeof a.utm_content?l(a.utm_content):""),k=1,[!0,[k,E,t,r,z,A].join("|")]):
""==B||null==B||"undefined"==B||(new RegExp("^https?://[\\w\\.]*?"+V+"($|/.*|:.*)")).test(B)?b&&0==c.length?(k=4,E=t=r=z=A="",[!0,[k,"||||"].join("|")]):[!1,c.join("|")]:(a=fa(B),2==a[0]||3==a[0]&&b?(k=a[0],E=a[1],z=a[4],t=r=A="",[!0,a.join("|")]):[!1,c.join("|")])},va=function(b){b=T(v);return"undefined"!=typeof b.zpclkid?b.zpclkid:""},ma=function(b){if(0==b.length)return!1;for(i in b)if(b.hasOwnProperty(i)&&sa.hasOwnProperty(b[i][0]))sa[b[i][0]](b[i]);return""==u?!1:!0};this.pageView=function(){"undefined"!=
typeof _zpq&&(f=ma(_zpq));"undefined"!=typeof _zampq&&(g=ma(_zampq));window.__zpSMConfig=window.__zpSMConfig||[];if(!g&&!f){for(;!g&&0<__zpSMConfig.length;){var k=__zpSMConfig.shift();k&&(g=ma(k.query||[]),qa=k.args,ca=k.nosp)}if(!g)return}p.__zp_smartpixel_list||(p.__zp_smartpixel_list={accout_map:{}});0<arguments.length?(B=v,v=arguments[0],v=v.replace(/\t|\n|\r/g,"")):(v=ra(),B=ea());wa({fun:function(c){I=c;c=new Date;c.setTime(c.getTime()+63072E6);var a=n=G=0,k=X=0;K=0;var r;r=String(Date.parse(new Date));
r=r.substr(0,r.length-3);var E="",q=va(v),z="",l=Y("__xsptplus"+u).split("#"),t=!1,A=[],C=0;if(!l||5>l.length)t=!0;else{var E=l[2],z=l[4],w=l[0].split("."),A=l[1].split("|");if(5!=w.length||6!=A.length)t=!0;else{G=w[1];a=w[2];k=w[3];K=w[4];try{C=(new Date(parseInt(k+"000"))).getDate()}catch(M){}1800<=r-k&&(t=!0);C!=(new Date(parseInt(r+"000"))).getDate()&&(t=!0)}}l=[!0,""];0<k&&(N=parseInt((r-k)/86400));t?(G++,U=1,J=q,K=0,a=r,l=ua(t,A)):(l=ua(t,A),p.__zp_smartpixel_list.accout_map&&"undefined"!=typeof p.__zp_smartpixel_list.accout_map[u]&&
(l[0]=!1),(t=l[0])?(G++,U=1,J=q,K=0,a=r):(J=E,n=r-a,X=r-k));k=T(v);k.zpclkid&&k.zpdl&&decodeURIComponent(k.zpdl)&&z!=k.zpclkid&&(z=k.zpclkid,ba=decodeURIComponent(k.zpdl));K++;na("__xsptplus"+u,u+"."+G+"."+a+"."+r+"."+K+"#"+l[1]+"#"+J+"#"+I+"#"+z,c,"/",V);p.__zp_smartpixel_list.accout_map||(p.__zp_smartpixel_list.accout_map={});p.__zp_smartpixel_list.accout_map[u]=1;ba&&d(ba,va(v));if(!ca){a=a=c="";if(g)a=ta(3);else if(f){c={};if("240"==m)c.ptype="homepage";else if("241"==m)c.ptype="regpage";else if("242"==
m)""!=e&&(c.userid=b(e)),c.ptype="regSuccPage";else if("243"==m)""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2]))),c.ptype="mycartPage";else if("244"==m)""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2]))),c.ptype="orderInfoPage";else if("245"==m)""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2]))),c.ptype="orderInfoPage";else if("246"==m)""!=e&&
(a=e.split(","),3<=a.length&&(c.productId=b(a[0]),c.inStock=b(a[1]),c.isWine=b(a[2]))),c.ptype="productPage";else if("247"==m)""!=e&&(a=e.split(","),4<=a.length&&(c.productId_list=b(a[0]),c.catname=b(a[1]),c.catid=b(a[2]),c.orderby=b(a[3]))),c.ptype="categoryPage";else if("248"==m)""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.keyword=b(a[1]),c.orderby=b(a[2]))),c.ptype="searchPage";else if("358"==m)""!=e&&(c.cityid=b(e)),c.ptype="homepage";else if("360"==m)""!=e&&(a=e.split(","),
2<=a.length&&(c.channelid=b(a[0]),c.categoryid=b(a[1]))),c.ptype="category";else if("361"==m)""!=e&&(c.productid=b(e)),c.ptype="detailpage";else if("362"==m)""!=e&&(c.productid=b(e)),c.ptype="shoppingcart";else if("457"==m)c.ptype="orderinfo";else if("809"==m)c.ptype="homepage";else if("810"==m)c.ptype="logregpage",""!=e&&(c.action=b(e));else if("811"==m)c.ptype="regSuccPage",""!=e&&(c.userid=b(e));else if("812"==m)c.ptype="searchPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),
c.keyword=b(a[1]),c.orderby=b(a[2])));else if("813"==m)c.ptype="categoryPage",""!=e&&(a=e.split(","),4<=a.length&&(c.productId_list=b(a[0]),c.catname=b(a[1]),c.catid=b(a[2]),c.orderby=b(a[3])));else if("814"==m)c.ptype="topicPage",""!=e&&(a=e.split(","),2<=a.length&&(c.productId_list=b(a[0]),c.topicName=b(a[1])));else if("815"==m)c.ptype="productPage",""!=e&&(a=e.split(","),2<=a.length&&(c.productId=b(a[0]),c.inStock=b(a[1])));else if("816"==m)c.ptype="mycartPage",""!=e&&(a=e.split(","),3<=a.length&&
(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("817"==m)c.ptype="orderInfoPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("818"==m)c.ptype="orderSuccPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("752"==m)c.ptype="homepage";else if("753"==m)c.ptype="regpage";else if("754"==m)c.ptype="regSuccPage";else if("755"==m)c.ptype="familysalesPage";
else if("756"==m)c.ptype="chanelPage",""!=e&&(c.chanelName=b(e));else if("757"==m)c.ptype="searchPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.keyword=b(a[1]),c.orderby=b(a[2])));else if("758"==m)c.ptype="categoryPage",""!=e&&(a=e.split(","),4<=a.length&&(c.productId_list=b(a[0]),c.catname=b(a[1]),c.brand=b(a[2]),c.orderby=b(a[3])));else if("759"==m)c.ptype="productPage",""!=e&&(a=e.split(","),4<=a.length&&(c.productId=b(a[0]),c.inStock=b(a[1]),c.inventoryDiv=b(a[2]),c.flashBuyTime=
b(a[3])));else if("760"==m)c.ptype="mycartPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("761"==m)c.ptype="orderInfoPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("762"==m)c.ptype="orderSuccPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("854"==m)c.ptype="homepage";else if("855"==m)c.ptype=
"logregpage",""!=e&&(c.action=b(e));else if("856"==m)c.ptype="regSuccPage",""!=e&&(c.userid=b(e));else if("857"==m)c.ptype="specialPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.keyword=b(a[1]),c.orderby=b(a[2])));else if("858"==m)c.ptype="promotionsPage",""!=e&&(a=e.split(","),2<=a.length&&(c.productId_list=b(a[0]),c.orderby=b(a[1])));else if("859"==m)c.ptype="topicPage",""!=e&&(a=e.split(","),2<=a.length&&(c.productId_list=b(a[0]),c.topicName=b(a[1])));else if("860"==m)c.ptype=
"productPage",""!=e&&(a=e.split(","),2<=a.length&&(c.productId=b(a[0]),c.inStock=b(a[1])));else if("861"==m)c.ptype="mycartPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("862"==m)c.ptype="orderInfoPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),c.totalNum=b(a[2])));else if("863"==m)c.ptype="orderSuccPage",""!=e&&(a=e.split(","),3<=a.length&&(c.productId_list=b(a[0]),c.totalPrice=b(a[1]),
c.totalNum=b(a[2])));else if(c.pagetype=R,""!=e)for(a=e.split(","),k=0;k<a.length;k++)c[R+"_k"+(k+1)]=b(a[k]).split(",");p.zamplus_tag_params=c;a=ta(3)}c=a[0];a=a[1];L=new S;p.__zp_smartpixel_list[c]||(p.__zp_smartpixel_list[c]=[]);p.__zp_smartpixel_list[c].push(L);L.src=a;U=0}da();""!=ka&&(a="a="+u+"&c="+ka+"&zid="+I+"&allow=0&type=23",""!=J&&(a=a+"&i="+h(J)),""!=la&&(a=a+"&info="+la),""!=v&&(a=a+"&u="+h(v)),""!=B&&(a=a+"&ru="+h(B)),a+="&r="+Math.random(),c=H("//ut.gtags.net/imp/conv")+"?"+a,2084<
c.length&&aa()&&(a=a.replace("&u="+h(v),""),c=(H("//ut.gtags.net/imp/conv")+"?argserror=true&"+a).substring(0,2084)),a=new S,p.__zp_smartpixel_list["//ut.gtags.net/imp/conv_"+u]=a,a.src=c);if(""!=ha&&!oa(W)){c="a="+u+"&t="+ha;for(var D in W)c+="&"+D+"="+h(F(W[D]));c+="&_="+(Math.random()+"").substr(2);D=H("//ut.gtags.net/imp/material")+"?"+c;2084<D.length&&aa()||(c=new S,p.__zp_smartpixel_list["//ut.gtags.net/imp/material"]=c,c.src=D)}},a:u,zid:Y("__xsptplus"+u).split("#")[3]});f&&(_zpq=[]);g&&(_zampq=
[])}}).pageView();window.__zampBroadcast||(window.__zampBroadcast=function(){try{var b=function(f,g){g=g||"opener.top";n[g]||l.push(f);for(var k=0,h;k<f.frames.length&&(h=f.frames[k]);k++)b(h,g+".frames["+k+"]")},g=function(b,d){d=d||"opener.top";if(b==opener)f=d;else for(var k=0,n;k<b.frames.length&&(n=b.frames[k]);k++)g(n,d+".frames["+k+"]")},f="",h=opener.top,l=[],n={};g(h);(function(b,d){var f=arguments.callee;l.push(b);n[d]=1;b.parent!=b&&f(b.parent,d.replace(/\.[^\.]+$/i,""))})(opener,f);b(h,
"");(function(){if(l[0]){var b=l.shift();try{b.postMessage({token:"catchLanding",landing:document.location.href,sourceUrl:ea(),sourceFramePath:f},"*")}catch(d){}setTimeout(arguments.callee,1)}})()}catch(p){}},window.__zampBroadcast());(function(){function b(){l||(l=1,clearInterval(h),h=setInterval(function(){null!=I&&null!=D&&(clearInterval(h),(new Image).src=H("//dat.gtags.net/imp/hm")+"?zid="+I+"&a="+D+"&u="+encodeURIComponent(document.location)+"&ru="+encodeURIComponent(ea())+"&_="+Math.random())},
50))}function g(){if(!navigator.userAgent.match(/android 4\.[0-3]/i))try{var f=function(k){k=k.accelerationIncludingGravity;h=k.x;_y=k.y;_z=k.z;if(Math.abs(h-_lastX)>g||Math.abs(_y-_lastY)>g||Math.abs(_z-_lastZ)>g)top.removeEventListener("devicemotion",f),b();_lastX=h;_lastY=_y;_lastZ=_z};if(top.addEventListener||top.removeEventListener){top.DeviceMotionEvent&&top.addEventListener("devicemotion",f,!1);var g=.04,h=_y=_z=_lastX=_lastY=_lastZ=0}}catch(k){}}function f(f){function g(p){clearTimeout(l);
l=setTimeout(function(){for(var l=0;l<h.length-1;l++){var p=h[l],q=h[l+1];if(null==p||null==q)return;if(p[0]!=q[0]||p[1]!=q[1]){l=f;p=g;l.removeEventListener?l.removeEventListener("mousemove",p,!1):l.detachEvent?l.detachEvent("onmousemove",p):l.onmousemove=null;b();return}}h=[];k=null},30);document.all?(x=p.clientX,y=p.clientY):(x=p.pageX,y=p.pageY);k&&h.push([x-k[0],y-k[1]]);k=[x,y]}var h=[],k,l;da(f,"mousemove",g)}if(!ca){var h,l=0;g();f(document.body)}})()})();
